"""Injectable byte-stream contract. Empty read means idle; EOFError means disconnection."""

from typing import Protocol


class Transport(Protocol):
    baud: int
    can_set_baud: bool

    async def open(self) -> None: ...
    async def read(self, size: int = 4096) -> bytes: ...
    async def write(self, data: bytes) -> None: ...
    async def set_baud(self, baud: int) -> None: ...
    async def close(self) -> None: ...
